services:
  pumpkin:
    build: .
    ports:
      - "25565:25565"
    volumes:
      - ./data:/pumpkin
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    stdin_open: true
    tty: true
